---
# defaults file for python-services
services:
  - name: "img-panda"
    install_path: "/img-app"
    resource_dir: "/img-app/resources"
    imports:
    - "from random import choice"
    - "from mimetypes import guess_type"
    - "from flask import send_from_directory"
    - "from os import listdir"
    flask:
      listen_address: "127.0.0.1"
      port: "8081"
      debug: false
      route_app: "/"
      methods:
      - "GET"

  - name: "smart-panda"
    install_path: "/smart-app"
    imports:
      - "from multiprocessing import Value"
      - "from flask import request"
    flask:
      listen_address: "127.0.0.1"
      port: "8082"
      debug: false
      route_app: "/"
      methods:
      - "GET"
      - "POST"


