---
# tasks file for python-services

- template:
    src: flask-app.j2
    dest: "/home/osboxes/projects/moises-bigpanda/roles/python-services/files/{{ item.name }}.py"
  with_items: "{{ services }}"