
- name: "Create the necessary directory for {{ service.name }}"
  file: path="{{ service.install_path }}" state=directory mode=0755

- name: "Copy the resources dir for img-service"

- name: "Rendering template for {{ service.name }}"
  template: src=flask-app.j2 dest="{{ service.install_path }}/app.py" mode=0755
  register: service_file

- name: "Render the {{ service.name }} upstart service"
  template: src=upstart.j2.conf dest=/etc/init/"{{ service.name }}".conf mode=0644

- name: "Restart {{ service.name }} service"
  service: name="{{ service.name }}" state=restarted
  when: service_file.changed